= Rancher CIS operator
:toc:
:toc-placement: preamble
:toclevels: 2
:showtitle:
:Some attr: Some value

// Need some preamble to get TOC:
{empty}

toc::[]

:sectnums:

== Introduction
=== Goals

. Understand hardening and CIS benchmarks in general
. Deploying and using Rancher CIS operator
. Understand how Rancher CIS scan and hardening


=== References
** https://www.cisecurity.org/benchmark/kubernetes[CIS Kubernetes Benchmark]
** https://rancher.com/docs/rancher/v2.5/en/cis-scans/[Rancher Docs - CIS Scans]
** https://github.com/rancher/cis-operator[Github - cis-operator]
** https://github.com/aquasecurity/kube-bench[kube-bench]
** https://github.com/vmware-tanzu/sonobuoy[sonobuoy]


=== Background
In this blog entry we cover deploying the Rancher CIS operator on RKE2 cluster, as well as other common tasks like do CIS scanning, getting CIS result and acting upon those results.


== What is Hardening and What is CIS Benchmark

*Hardening*, is the practice of reducing a system’s vulnerability exposure by reducing its attack surface. So when you perform system hardening you basically try to reduce the entry points where attackers can use.

The Center for Internet Security (*CIS*) is a 501 nonprofit organization, formed in October, 2000. Its mission is to make the connected world a safer place by developing, validating, and promoting timely best practice solutions that help people, businesses, and governments protect themselves against pervasive cyber threats. Wikipedia

*CIS Benchmark* is a set of recommendations for configuring Kubernetes to support a strong security posture. The Benchmark is tied to a specific Kubernetes release. https://www.cisecurity.org/benchmark/kubernetes[]

So CIS Benchmarks is mainly focused on hardening two aspects,

* K8s components hardening like API server, Etcd, kubelet, kube-proxy
* Node hardening 


== Deploying and using Rancher CIS operator
Rancher can run a security scan to check whether Kubernetes is deployed according to security best practices as defined in the CIS Kubernetes Benchmark. The CIS scans can run on any Kubernetes cluster, including hosted Kubernetes providers such as EKS, AKS, and GKE.

The rancher-cis-benchmark app leverages kube-bench, an open-source tool from Aqua Security, to check clusters for CIS Kubernetes Benchmark compliance. Also, to generate a cluster-wide report, the application utilizes Sonobuoy for report aggregation.

You can use rancher to deploy Rancher CIS operator to any of the downstream clusters, for mor info. please see https://rancher.com/docs/rancher/v2.5/en/cis-scans/#installing-rancher-cis-benchmark[]

In this post we will not use Rancher but rather deploy the rancher-cis-benchmark helm app directly.

so lets inspect the rancher-cis-benchmark helm chart.

=== Deploying CIS operator

. Add Rancher Helm repo
+
[source,bash]
----
$ helm repo add rancher https://charts.rancher.io
"rancher" has been added to your repositories
----
+
[source,bash]
----
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "rancher" chart repository
Update Complete. ⎈Happy Helming!⎈
----
. Find the helm package name
+
[source,bash]
----
$ helm search repo cis-benchmark
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
rancher/rancher-cis-benchmark           2.0.2           v2.0.2          The cis-operator enables running CIS benchmark ...
rancher/rancher-cis-benchmark-crd       2.0.2                           Installs the CRDs for rancher-cis-benchmark.
----
. Now lets see the package information, this is useful if you want to change the default values
+
[source,bash]
----
$ helm show all rancher/rancher-cis-benchmark
annotations:
  catalog.cattle.io/auto-install: rancher-cis-benchmark-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: CIS Benchmark
  catalog.cattle.io/kube-version: '>=1.16.0-0'
  catalog.cattle.io/namespace: cis-operator-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/provides-gvr: cis.cattle.io.clusterscans/v1
  catalog.cattle.io/rancher-version: '>= 2.6.0-0'
  catalog.cattle.io/release-name: rancher-cis-benchmark
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: rancher-cis-benchmark
apiVersion: v1
appVersion: v2.0.2
description: The cis-operator enables running CIS benchmark security scans on a kubernetes
  cluster
icon: https://charts.rancher.io/assets/logos/cis-kube-bench.svg
keywords:
- security
name: rancher-cis-benchmark
version: 2.0.2

---
# Default values for rancher-cis-benchmark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.6
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.5
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.53.2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  cattle:
    systemDefaultRegistry: ""
    clusterName: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2

alerts:
  enabled: false
  severity: warning
  metricsPort: 8080

---
# Rancher CIS Benchmark Chart

The cis-operator enables running CIS benchmark security scans on a kubernetes cluster and generate compliance reports that can be downloaded.

# Installation

```
helm install rancher-cis-benchmark ./ --create-namespace -n cis-operator-system
```
----
+
[source,bash]
----
$ helm show all rancher/rancher-cis-benchmark-crd
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cis-operator-system
  catalog.cattle.io/release-name: rancher-cis-benchmark-crd
apiVersion: v1
description: Installs the CRDs for rancher-cis-benchmark.
name: rancher-cis-benchmark-crd
type: application
version: 2.0.2


# rancher-cis-benchmark-crd
A Rancher chart that installs the CRDs used by rancher-cis-benchmark.

----
. Deploy rancher-cis-benchmark (we will use the default values now)
+
[source,bash]
----
$ helm install rancher-cis-benchmark-crd rancher/rancher-cis-benchmark-crd --create-namespace -n cis-operator-system
NAME: rancher-cis-benchmark-crd
LAST DEPLOYED: Mon Mar  7 15:18:16 2022
NAMESPACE: cis-operator-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
+
[source,bash]
----
$ helm install rancher-cis-benchmark rancher/rancher-cis-benchmark -n cis-operator-system
NAME: rancher-cis-benchmark
LAST DEPLOYED: Mon Mar  7 15:18:38 2022
NAMESPACE: cis-operator-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
. To make it easy for me i will create a Kube context for the cis-operator-system namesapce
+
[source,bash]
----
$ kubectl config set-context cis --cluster=default --namespace=cis-operator-system --user=default
Context "cis" created.
----
+
[source,bash]
----
$ kubectl config use-context cis
Switched to context "cis".
----
+
[source,bash]
----
$ kubectl get all
NAME                                READY   STATUS    RESTARTS   AGE
pod/cis-operator-649df6ff45-g9kgd   1/1     Running   0          7m57s

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cis-operator   1/1     1            1           7m57s

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/cis-operator-649df6ff45   1         1         1       7m57s
----

=== CIS Operator CRDs (types)

==== CIS Benchmarks -- ClusterScanBenchmark
So as mentioned before that each K8s version (and sometimes distribution) have a CIS benchmark, This is mapped in CIS operator to ClusterScanBenchmark. 

A ClusterScanBenchmark is the wrapper of kube-bench. It defines the CIS BenchmarkVersion name and test configurations. The BenchmarkVersion name is a parameter provided to the kube-bench tool.

By default, a few BenchmarkVersion names and test configurations are packaged as part of the CIS scan application.

[source,bash]
----
$ kubectl get clusterscanbenchmarks
NAME                      CLUSTERPROVIDER   MINKUBERNETESVERSION   MAXKUBERNETESVERSION   CUSTOMBENCHMARKCONFIGMAPNAME   CUSTOMBENCHMARKCONFIGMAPNAMESPACE
cis-1.5                                     1.15.0
cis-1.6                                     1.16.0
eks-1.0                   eks               1.15.0
gke-1.0                   gke               1.15.0
k3s-cis-1.6-hardened      k3s               1.20.5
k3s-cis-1.6-permissive    k3s               1.20.5
rke-cis-1.5-hardened      rke               1.15.0
rke-cis-1.5-permissive    rke               1.15.0
rke-cis-1.6-hardened      rke               1.16.0
rke-cis-1.6-permissive    rke               1.16.0
rke2-cis-1.5-hardened     rke2              1.18.0
rke2-cis-1.5-permissive   rke2              1.18.0
rke2-cis-1.6-hardened     rke2              1.20.5
rke2-cis-1.6-permissive   rke2              1.20.5
----

https://rancher.com/docs/rancher/v2.5/en/cis-scans/#test-profiles[]

There are two types of scan benchmarks:

*Permissive:* This profile has a set of tests that have been will be skipped as these tests will fail on a default RKE Kubernetes cluster. Besides the list of skipped tests, the profile will also not run the not applicable tests.

*Hardened:* This profile will not skip any tests, except for the non-applicable tests.

It is also possible to create a custom Benchmark Version using the rancher-cis-benchmark application, for more info. please see https://rancher.com/docs/rancher/v2.5/en/cis-scans/custom-benchmark/[]. This is useful when you have another industry standard or organization specif standard you want to compliy with, like HIPAA or others   


==== Scan profiles -- ClusterScanProfiles
A scan profile contains the configuration for the CIS scan, which includes the benchmark version to use and any specific tests to skip in that benchmark. So for the same ClusterScanBenchmark we can have multiple ClusterScanProfiles with . it is advisable for users to not edit the default ClusterScanProfiles

[source,bash]
----
$ kubectl get clusterscanprofiles
NAME                              BENCHMARKVERSION
cis-1.5-profile                   cis-1.5
cis-1.6-profile                   cis-1.6
eks-profile                       eks-1.0
gke-profile                       gke-1.0
k3s-cis-1.6-profile-hardened      k3s-cis-1.6-hardened
k3s-cis-1.6-profile-permissive    k3s-cis-1.6-permissive
rke-profile-hardened-1.5          rke-cis-1.5-hardened
rke-profile-hardened-1.6          rke-cis-1.6-hardened
rke-profile-permissive-1.5        rke-cis-1.5-permissive
rke-profile-permissive-1.6        rke-cis-1.6-permissive
rke2-cis-1.5-profile-hardened     rke2-cis-1.5-hardened
rke2-cis-1.5-profile-permissive   rke2-cis-1.5-permissive
rke2-cis-1.6-profile-hardened     rke2-cis-1.6-hardened
rke2-cis-1.6-profile-permissive   rke2-cis-1.6-permissive
----

==== Scans -- ClusterScan
A scan is created to trigger a CIS scan on the cluster based on the defined profile. A report is created after the scan is completed.

So, When a cluster scan runs, it points to a specific Scan Profile which points to a specific Benchmark Version. This is how things linked together.

for selecting the right Benchmark Versions, please refer to https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/#rke-guides[Hardening Guides and Benchmark Versions]

So lets create a scan by using the following clusterscan configuration

.xref:rke2-clusterscan.yaml[rke2-clusterscan.yaml]
[source,yaml]
----
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  name: rke2-clusterscan
spec:
  scanProfileName: rke2-cis-1.6-permissive
----

[source,bash]
----
$ kubectl apply -f rke2-clusterscan.yaml
----